serviceCIDR: "10.96.0.0/16"
serviceCIDRv6: "fd12:3456:789a:1000::/56"
antreaProxy:
  # To disable AntreaProxy, set this to false.
  enable: true
  # TODO figure out how to skip installing kube-proxy
  proxyAll: true