# For options see: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
# https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/
# see: https://kubernetes.io/docs/concepts/services-networking/dual-stack/#configure-ipv4-ipv6-dual-stack
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
cgroupDriver: systemd
clusterDNS:
- fd12:3456:789a:2000::10
- 10.96.0.10
clusterDomain: cluster.local
containerRuntimeEndpoint: "unix:///var/run/containerd/containerd.sock"
healthzBindAddress: ::1
healthzPort: 10248
imageMinimumGCAge: 4h
kind: KubeletConfiguration
logging:
  flushFrequency: 0
  options:
    json:
      infoBufferSize: "0"
    text:
      infoBufferSize: "0"
  verbosity: 0
resolvConf: /run/systemd/resolve/resolv.conf
runtimeRequestTimeout: 10s
shutdownGracePeriod: 60s
shutdownGracePeriodCriticalPods: 15s
staticPodPath: /etc/kubernetes/manifests
serverTLSBootstrap: true
rotateCertificates: true
