apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 2600:1f16:1ce1:3302:29cf:b10c:b8fb:66aa
  bindPort: 6443
name: control-plane-01
nodeRegistration:
  kubeletExtraArgs:
    - name: node-ip
      value: 2600:1f16:1ce1:3302:29cf:b10c:b8fb:66aa,10.96.138.24
    - name: image-credential-provider-config
      value: /var/lib/kubelet/credential-provider-config.yaml
    - name: image-credential-provider-bin-dir
      value: /usr/local/bin
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: 1.34.0
networking:
  dnsDomain: cluster.local
  podSubnet: fd12:3456:789a:1000::/56,10.244.0.0/16
  serviceSubnet: fd12:3456:789a:2000::/112,10.96.0.0/16
controlPlaneEndpoint: control-plane
apiServer:
  # When you set the advertiseAddress to a non-loopback address, you must add
  # the loopback address to the certSANs list.
  certSANs:
   - ::1
   - 0:0:0:0:0:0:0:1
   - 2600:1f16:1ce1:3302:29cf:b10c:b8fb:66aa
   - 127.0.0.1
   - 10.96.138.24
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
featureGates:
  KubeletServiceAccountTokenForCredentialProviders: true
